name: 'Lighthouse Report Tracker'
description: 'Automatically store and analyze Lighthouse CI reports. No external server/storage required.'
inputs:
  secret:
    description: 'The GitHub token required for API requests to create comments in pull requests. GitHub generates the token at the start of the workflow'
    required: true
  outputDir:
    description: 'The directory configured in your lighthouserc.js.'
    default: './lhci'
runs:
  using: 'node20'
  main: 'src/index.js'
branding:
  icon: 'activity'
  color: 'white'
